### PR TITLE
Fix tabs not closing properly

### LINKED ISSUE #20: Small amount of tabs are retained after restart
Some tabs (like 10%) seem to close, but when using Ctrl/⌘+[0-9], they are still present, and will retain after restarting Firefox.

## Device
Firefox 85.0a1 on macOS 11.0.1 Big Sur

### PR DESCRIPTION
**Pull request by radiolevity**
I believe this PR fixes #20 as per Bugzilla [585417](https://bugzilla.mozilla.org/show_bug.cgi?id=585417).

### CODE REVIEW

**Comment by semihcanturk** [comment]
hmm, this seems to have broken some things for me - not sure if that's the case for anyone else. Should I make an issue for it?

image

**Comment by radiolevity** [comment]
I can't seem to replicate this issue. Do you have anything else in your userChrome?

**Comment by semihcanturk** [comment]
Nope, my userChrome in the profile folder is just the import statement. I deleted and recloned the repo for good measure, but the issue still persists. In light mode it works just fine, by the way - it's only the dark mode where it gets messed up (which seems that only the main bar background color doesn't get darker). Do you not encounter this if you toggle between light/dark mode?

**Comment by ideaweb** [comment]
Confirmed, I have the same issue with userChrome-vibrancy.css. Something changed but i think this has nothing todo with this pull request.

**Comment by semihcanturk** [comment]
Ah, okay. I'll make a separate issue on this then.

**Pull request merged**
